name: Tag Fuzzing
description: Test which HTML tags survive sanitization
body:
  - type: checkboxes
    id: standard-html
    attributes:
      label: Standard HTML Tags
      options:
        - label: '<a href="//evil.com">asasas</a>'
       
